config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  # get 'tasks/:id', to: 'tasks#show', as: :show
  get 'tasks/:id', to: 'tasks#show', as: :task
  patch 'tasks/:id', to: 'tasks#update'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  delete 'tasks/:id', to: 'tasks#destroy'
  # get 'tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    if @task.completed == false
      @completed = 'This task is not completed yet'
    else
      @completed = 'This task is completed'
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1 class="mt-5">Edit your task:</h1>
  <%= form_with model: @task do |f| %>
    <div class="mb-3"><%= f.label :title %>
    <%= f.text_field :title %></div>
    <div class="mb-3"><%= f.label :details %>
    <%= f.text_area :details %></div>
    <div class="mb-3"><%= f.label :completed %>
    <%= f.check_box :completed %></div>
    <%= f.submit %>
  <% end %>

  <div class="mt-5"><%= link_to "Back to tasks", tasks_path %></div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="mt-5">My tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
    <li>
    <% if task.completed == false %>
      <i id="not-done" class="fa-regular fa-square"></i> <%= link_to task.title, task_path(task) %>
    <% else %>
      <i id="done" class="fa-regular fa-square-check"></i> <%= link_to task.title, task_path(task) %>
    <% end %>
    </li>
    <% end %>
  </ul>
  <%= link_to 'Add a new task', tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1 class="mt-5">Add a new task:</h1>
  <%= form_with model: @task do |f| %>
    <div class="mb-3"><%= f.label :title %>
    <%= f.text_field :title %></div>
    <div class="mb-3"><%= f.label :details %>
    <%= f.text_area :details %></div>
    <%= f.submit %>
  <% end %>

  <div class="mt-5"><%= link_to "Back to tasks", tasks_path %></div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1 class="mt-5"><%= @task.title %></h1>
  <div class="alert-secondary p-3 mb-3"><%= @task.details %></div>
  <p><%= @completed %></p>
  <br>
  <%= link_to "Back to tasks", tasks_path %>
  <br>
  <%= link_to "Edit", edit_path %>
  <br>
  <%= link_to "Delete",
    task_path(@task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
</div>